public: public
assets: assets
podcast:
  base_url: ""
  feed_url: "feed.xml"
  url: ""
  author: atareao
  email: atareao@atareao.es
  image_url: https://rustacean.net/assets/cuddlyferris.png 
  category: Technology
  subcategory:
  explicit: false
  title: Diario de un crustáceo
  description: Donde cuento mis aventuras y desventuras en Rust y Linux
  keywords:
    - rust
    - rustacean
    - crate
    - linux
    - neovim
  license:  CC BY 4.0 Deed
iaclient:
  uploader: atareao
  podcast: Diario de un crustáceo
